// <auto-generated />
using IPDTrackerWebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IPDTrackerWebApp.Data.Migrations
{
    [DbContext(typeof(IPDContext))]
    partial class IPDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("IPDTrackerWebApp.Model.BillingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BillingDate");

                    b.Property<TimeSpan>("BillingTime");

                    b.Property<string>("ClientName");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Notes");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("BillingEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
